FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env

COPY . /app
WORKDIR /app

RUN dotnet restore

RUN dotnet publish -o build-results

FROM mcr.microsoft.com/dotnet/aspnet:6.0

COPY --from=build-env /app/build-results .
WORKDIR /app
CMD ["dotnet", "AspNetDemo.dll"]